module.exports = {
  docs: [
    'intro',
    'card-import-mongodb',
    {
      type: 'category',
      label: 'Especificaciones arquitectónicas',
      items: [
        {
          type: 'autogenerated',
          dirName: 'superpowers/specs',
        },
      ],
    },
  ],
};
