services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: card-sync-service
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command:
      ["sh", "-c", "pnpm prisma generate && pnpm build && exec pnpm start:prod"]
    expose:
      - "80"
    networks:
      - default

volumes:
  node_modules:

networks:
  default:
    external: true
    name: carddock-network
